# Dev 分支推送部署预览
## 仅部署 Win 端
name: Build Dev

on:
  push:
    branches:
      - dev
      - master
      - ci-test

jobs:
  release:
    name: Build Website
    runs-on: windows-latest

    steps:
      # 检出 Git 仓库
      - name: Check out git repository
        uses: actions/checkout@v4.1.1
      # 安装 Node.js
      - name: Install Node.js
        uses: actions/setup-node@v4.0.0
        with:
          node-version: "18.x"
      # 安装项目依赖
      - name: Install Dependencies
        run: npm install
      # 构建程序
      - name: Build Website
        run: npm run build
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          VITE_WEATHER_KEY: ${{ secrets.VITE_WEATHER_KEY }}

          VITE_SITE_NAME: ${{ vars.VITE_SITE_NAME }}
          VITE_SITE_AUTHOR: ${{ vars.VITE_SITE_AUTHOR }}
          VITE_SITE_KEYWORDS: ${{ vars.VITE_SITE_KEYWORDS }}
          VITE_SITE_DES: ${{ vars.VITE_SITE_DES }}
          VITE_SITE_URL: ${{ vars.VITE_SITE_URL }}
          VITE_SITE_LOGO: ${{ vars.VITE_SITE_LOGO }}
          VITE_SITE_MAIN_LOGO: ${{ vars.VITE_SITE_MAIN_LOGO }}
          VITE_SITE_APPLE_LOGO: ${{ vars.VITE_SITE_APPLE_LOGO }}
          VITE_DESC_HELLO: ${{ vars.VITE_DESC_HELLO }}
          VITE_DESC_TEXT: ${{ vars.VITE_DESC_TEXT }}
          VITE_DESC_HELLO_OTHER: ${{ vars.VITE_DESC_HELLO_OTHER }}
          VITE_DESC_TEXT_OTHER: ${{ vars.VITE_DESC_TEXT_OTHER }}
          VITE_SITE_START: ${{ vars.VITE_SITE_START }}
          VITE_SITE_ICP: ${{ vars.VITE_SITE_ICP }}
          VITE_SONG_API: ${{ vars.VITE_SONG_API }}
          VITE_SONG_SERVER: ${{ vars.VITE_SONG_SERVER }}
          VITE_SONG_TYPE: ${{ vars.VITE_SONG_TYPE }}
          VITE_SONG_ID: ${{ vars.VITE_SONG_ID }}

      # 上传构建产物
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.4.3
        with:
          name: Home
          path: dist

      # 部署到服务器
      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASS }}
          server-dir: dist/
